---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart SMB service
  ansible.builtin.service:
    name: "{{ smb_service }}"
    state: restarted

- name: Restart NMB service
  ansible.builtin.service:
    name: "{{ nmb_service }}"
    state: restarted
  when: samba_enable_netbios | bool

- name: Restart samba-ad-dc
  ansible.builtin.service:
    name: samba-ad-dc
