---
samba_packages:
  - samba
  - samba-client

samba_vfs_packages: []

samba_configuration_dir: /etc/samba
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
samba_username_map_file: "{{ samba_configuration_dir }}/smbusers"

smb_service: smb
nmb_service: nmb

samba_www_documentroot: /var/www/html

samba_acl_packages:
  - acl
