---
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Draft release
    runs-on: ubuntu-22.04
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
